name: Tests

on:
    push:
        branches:
            - 'master'
            - '[0-9].[0-9]+'
    pull_request: ~

jobs:
    tests:
        name: ${{ matrix.php }} ${{ matrix.coverage }} ${{ matrix.engine }} ${{ matrix.regression }} ${{ matrix.core_setup }}
        runs-on: ubuntu-latest
        env:
            extensions: pdo_sqlite

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php: '7.2'
                      coverage: 'unit'
                      config: 'phpunit.xml'
                    - php: '7.2'
                      coverage: 'integration'
                      engine: 'legacy'
                      config: 'phpunit-integration-legacy.xml'
                    - php: '7.2'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '8.11.2'
                      core_setup: 'dedicated'
                    - php: '7.2'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'vendor/ezsystems/ezpublish-kernel/phpunit-integration-legacy-solr.xml'
                      solr_version: '8.11.2'
                      core_setup: 'shared'
                      regression: 'regression'

                    - php: '7.3'
                      coverage: 'unit'
                      config: 'phpunit.xml'
                    - php: '7.3'
                      coverage: 'integration'
                      engine: 'legacy'
                      config: 'phpunit-integration-legacy.xml'
                    - php: '7.3'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '8.11.2'
                      core_setup: 'dedicated'
                    - php: '7.3'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'vendor/ezsystems/ezpublish-kernel/phpunit-integration-legacy-solr.xml'
                      solr_version: '8.11.2'
                      core_setup: 'shared'
                      regression: 'regression'

                    - php: '7.4'
                      coverage: 'unit'
                      config: 'phpunit.xml'
                    - php: '7.4'
                      coverage: 'integration'
                      engine: 'legacy'
                      config: 'phpunit-integration-legacy.xml'
                    - php: '7.4'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '8.11.2'
                      core_setup: 'dedicated'
                    - php: '7.4'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'vendor/ezsystems/ezpublish-kernel/phpunit-integration-legacy-solr.xml'
                      solr_version: '8.11.2'
                      core_setup: 'shared'
                      regression: 'regression'

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: 8
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: ${{ env.extensions }}

            - run: composer --version
            - run: composer validate --strict
            - run: COMPOSER_ROOT_VERSION=1.99 composer update --prefer-dist
            - run: SOLR_VERSION=${{ matrix.solr_version }} SOLR_CORES=${{ matrix.solr_cores }} ./bin/.travis/init_solr.sh
              if: matrix.solr_version
            - run: |
                  sed -i.bak s/EzSystems\\\\EzPlatformSolrSearchEngine\\\\Tests\\\\SetupFactory\\\\LegacySetupFactory/Netgen\\\\EzPlatformSearchExtra\\\\Tests\\\\Integration\\\\SetupFactory\\\\Solr/g ${{ matrix.config }}
                  sed -i.bak "s/eZ\/Publish\/API\/Repository\/Tests\/SearchServiceTest.php/..\/..\/..\/tests\/lib\/Kernel\/SearchServiceTest.php/g" ${{ matrix.config }}
                  sed -i.bak "s/eZ\/Publish\/API\/Repository\/Tests\/SearchServiceLocationTest.php/..\/..\/..\/tests\/lib\/Kernel\/SearchServiceLocationTest.php/g" ${{ matrix.config }}
              if: matrix.regression
            - run: CORES_SETUP=${{ matrix.core_setup }} vendor/bin/phpunit --bootstrap tests/bootstrap.php -c ${{ matrix.config }} --colors=always
